-- MySQL Script generated by MySQL Workbench
-- Fri Jan 12 16:10:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SAE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SAE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SAE` DEFAULT CHARACTER SET utf8 ;
USE `SAE` ;

-- -----------------------------------------------------
-- Table `SAE`.`Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`Adresse` (
  `idAdresse` INT NOT NULL AUTO_INCREMENT,
  `adresse` TEXT NULL,
  `codePostal` TEXT NULL,
  `ville` TEXT NULL,
  PRIMARY KEY (`idAdresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `Adresse_idAdresse` INT NULL,
  `raisonSociale` TEXT NULL,
  `civilite` TEXT NULL,
  `nom` TEXT NULL,
  `prenom` TEXT NULL,
  `telephone` TEXT NULL,
  `telephone2` TEXT NULL,
  `telephone3` TEXT NULL,
  `mail` TEXT NULL,
  `profession` TEXT NULL,
  `dateNaissance` DATE NULL,
  `motDePasse` TEXT NULL,
  `estDispense` TINYINT NULL,
  `imageProfil` MEDIUMBLOB NULL,
  `token` TEXT NULL,
  PRIMARY KEY (`idClient`),
  CONSTRAINT `fk_Client_Adresse1`
    FOREIGN KEY (`Adresse_idAdresse`)
    REFERENCES `SAE`.`Adresse` (`idAdresse`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`Referent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`Referent` (
  `idReferent` INT NOT NULL AUTO_INCREMENT,
  `nom` TEXT NULL,
  `mail` TEXT NULL,
  `telephone` TEXT NULL,
  PRIMARY KEY (`idReferent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`Depot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`Depot` (
  `idDepot` INT NOT NULL AUTO_INCREMENT,
  `Adresse_idAdresse` INT NOT NULL,
  `Referent_idReferent` INT NOT NULL,
  `estArchive` TINYINT NULL,
  `nom` TEXT NULL,
  `presentation` LONGTEXT NULL,
  `image` MEDIUMBLOB NULL,
  `commentaire` LONGTEXT NULL,
  `website` TEXT NULL,
  `mail` TEXT NULL,
  `telephone` TEXT NULL,
  PRIMARY KEY (`idDepot`),
  CONSTRAINT `fk_Depot_Adresse1`
    FOREIGN KEY (`Adresse_idAdresse`)
    REFERENCES `SAE`.`Adresse` (`idAdresse`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Depot_Referent1`
    FOREIGN KEY (`Referent_idReferent`)
    REFERENCES `SAE`.`Referent` (`idReferent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`JourSemaine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`JourSemaine` (
  `idJourSemaine` INT NOT NULL AUTO_INCREMENT,
  `nom` TEXT NULL,
  PRIMARY KEY (`idJourSemaine`))
ENGINE = InnoDB
PACK_KEYS = 1;


-- -----------------------------------------------------
-- Table `SAE`.`PeriodeNonLivrable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`PeriodeNonLivrable` (
  `idPeriode` INT NOT NULL AUTO_INCREMENT,
  `Depot_idDepot` INT NOT NULL,
  `debut` DATE NULL,
  `fin` DATE NULL,
  PRIMARY KEY (`idPeriode`),
  CONSTRAINT `fk_PeriodeNonLivrable_Depot1`
    FOREIGN KEY (`Depot_idDepot`)
    REFERENCES `SAE`.`Depot` (`idDepot`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`JourOuvrable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`JourOuvrable` (
  `Depot_idDepot` INT NOT NULL,
  `JourSemaine_idJourSemaine` INT NOT NULL,
  PRIMARY KEY (`Depot_idDepot`, `JourSemaine_idJourSemaine`),
  CONSTRAINT `fk_Depot_has_JourSemaine_Depot`
    FOREIGN KEY (`Depot_idDepot`)
    REFERENCES `SAE`.`Depot` (`idDepot`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Depot_has_JourSemaine_JourSemaine1`
    FOREIGN KEY (`JourSemaine_idJourSemaine`)
    REFERENCES `SAE`.`JourSemaine` (`idJourSemaine`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`Tournee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`Tournee` (
  `idTournee` INT NOT NULL AUTO_INCREMENT,
  `jourPreparation` INT NOT NULL,
  `jourLivraison` INT NOT NULL,
  `nom` TEXT NULL,
  `couleur` TEXT NULL,
  `estMatin` BIT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idTournee`),
  CONSTRAINT `fk_Tournee_JourSemaine1`
    FOREIGN KEY (`jourPreparation`)
    REFERENCES `SAE`.`JourSemaine` (`idJourSemaine`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Tournee_JourSemaine2`
    FOREIGN KEY (`jourLivraison`)
    REFERENCES `SAE`.`JourSemaine` (`idJourSemaine`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`Tournee_has_Depot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`Tournee_has_Depot` (
  `Tournee_idTournee` INT NOT NULL,
  `Depot_idDepot` INT NOT NULL,
  `ordre` INT NULL,
  PRIMARY KEY (`Tournee_idTournee`, `Depot_idDepot`),
  CONSTRAINT `fk_Tournee_has_Depot_Tournee1`
    FOREIGN KEY (`Tournee_idTournee`)
    REFERENCES `SAE`.`Tournee` (`idTournee`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Tournee_has_Depot_Depot1`
    FOREIGN KEY (`Depot_idDepot`)
    REFERENCES `SAE`.`Depot` (`idDepot`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`Jardin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`Jardin` (
  `idJardin` INT NOT NULL AUTO_INCREMENT,
  `Referent_idReferent` INT NOT NULL,
  `Adresse_idAdresseSiegeSocial` INT NOT NULL,
  `Adresse_idAdresseGestion` INT NOT NULL,
  `nomCommercial` TEXT NULL,
  `raison` TEXT NULL,
  PRIMARY KEY (`idJardin`),
  CONSTRAINT `fk_Jardin_Client1`
    FOREIGN KEY (`Referent_idReferent`)
    REFERENCES `SAE`.`Referent` (`idReferent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Jardin_Adresse1`
    FOREIGN KEY (`Adresse_idAdresseSiegeSocial`)
    REFERENCES `SAE`.`Adresse` (`idAdresse`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Jardin_Adresse2`
    FOREIGN KEY (`Adresse_idAdresseGestion`)
    REFERENCES `SAE`.`Adresse` (`idAdresse`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`TypeAdhesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`TypeAdhesion` (
  `idTypeAdhesion` INT NOT NULL AUTO_INCREMENT,
  `nom` TEXT NULL,
  `tarif` DECIMAL NULL,
  PRIMARY KEY (`idTypeAdhesion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`Facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`Facture` (
  `idFacture` INT NOT NULL AUTO_INCREMENT,
  `estPaye` TINYINT NULL,
  `prix` DECIMAL NULL,
  PRIMARY KEY (`idFacture`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`Adhesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`Adhesion` (
  `idAdhesion` INT NOT NULL AUTO_INCREMENT,
  `Client_idClient` INT NOT NULL,
  `TypeAdhesion_idTypeAdhesion` INT NOT NULL,
  `Jardin_idJardin` INT NOT NULL,
  `debut` DATE NULL,
  `fin` DATE NULL,
  `Facture_idFacture` INT NULL,
  `enCours` BIT NULL,
  `frequencePaiement` INT NULL,
  PRIMARY KEY (`idAdhesion`),
  CONSTRAINT `fk_Adhesion_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `SAE`.`Client` (`idClient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Adhesion_TypeAdhesion1`
    FOREIGN KEY (`TypeAdhesion_idTypeAdhesion`)
    REFERENCES `SAE`.`TypeAdhesion` (`idTypeAdhesion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Adhesion_Jardin1`
    FOREIGN KEY (`Jardin_idJardin`)
    REFERENCES `SAE`.`Jardin` (`idJardin`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Adhesion_Facture1`
    FOREIGN KEY (`Facture_idFacture`)
    REFERENCES `SAE`.`Facture` (`idFacture`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`Panier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`Panier` (
  `idPanier` INT NOT NULL AUTO_INCREMENT,
  `nom` TEXT NULL,
  `prix` DECIMAL NULL,
  `image` MEDIUMBLOB NULL,
  `Jardin_idJardin` INT NOT NULL,
  PRIMARY KEY (`idPanier`),
  CONSTRAINT `fk_Panier_Jardin1`
    FOREIGN KEY (`Jardin_idJardin`)
    REFERENCES `SAE`.`Jardin` (`idJardin`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`Unite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`Unite` (
  `idUnite` INT NOT NULL AUTO_INCREMENT,
  `nom` TEXT NULL,
  PRIMARY KEY (`idUnite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`Produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`Produit` (
  `idProduit` INT NOT NULL AUTO_INCREMENT,
  `Unite_idUnite` INT NOT NULL,
  `nom` TEXT NULL,
  `image` MEDIUMBLOB NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`idProduit`),
  CONSTRAINT `fk_Produit_Unite1`
    FOREIGN KEY (`Unite_idUnite`)
    REFERENCES `SAE`.`Unite` (`idUnite`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`Produit_has_Panier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`Produit_has_Panier` (
  `Produit_idProduit` INT NOT NULL,
  `Panier_idPanier` INT NOT NULL,
  `quantite` INT NULL,
  PRIMARY KEY (`Produit_idProduit`, `Panier_idPanier`),
  CONSTRAINT `fk_Produit_has_Panier_Produit1`
    FOREIGN KEY (`Produit_idProduit`)
    REFERENCES `SAE`.`Produit` (`idProduit`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Produit_has_Panier_Panier1`
    FOREIGN KEY (`Panier_idPanier`)
    REFERENCES `SAE`.`Panier` (`idPanier`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`Abonnement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`Abonnement` (
  `idAbonnement` INT NOT NULL AUTO_INCREMENT,
  `Client_idClient` INT NOT NULL,
  `Panier_idPanier` INT NOT NULL,
  `debut` DATE NULL,
  `fin` DATE NULL,
  `estActif` BIT NULL,
  `frequenceLivraison` INT NULL DEFAULT 30,
  PRIMARY KEY (`idAbonnement`),
  CONSTRAINT `fk_Client_has_Abonnement_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `SAE`.`Client` (`idClient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Client_has_Abonnement_Abonnement1`
    FOREIGN KEY (`Panier_idPanier`)
    REFERENCES `SAE`.`Panier` (`idPanier`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`Livraison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`Livraison` (
  `idLivraison` INT NOT NULL AUTO_INCREMENT,
  `Abonnement_idAbonnement` INT NOT NULL,
  `Depot_idDepot` INT NULL,
  `Tournee_idTournee` INT NULL,
  `semaine` DATE NULL,
  `etat` INT NULL,
  PRIMARY KEY (`idLivraison`),
  CONSTRAINT `fk_Livraison_Depot1`
    FOREIGN KEY (`Depot_idDepot`)
    REFERENCES `SAE`.`Depot` (`idDepot`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Livraison_Tournee1`
    FOREIGN KEY (`Tournee_idTournee`)
    REFERENCES `SAE`.`Tournee` (`idTournee`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Livraison_ClientAbonnement1`
    FOREIGN KEY (`Abonnement_idAbonnement`)
    REFERENCES `SAE`.`Abonnement` (`idAbonnement`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAE`.`Abonnement_has_Facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAE`.`Abonnement_has_Facture` (
  `Abonnement_idClientAbonnement` INT NOT NULL,
  `Facture_idFacture` INT NOT NULL,
  PRIMARY KEY (`Abonnement_idClientAbonnement`, `Facture_idFacture`),
  CONSTRAINT `fk_Abonnement_has_Facture_Abonnement1`
    FOREIGN KEY (`Abonnement_idClientAbonnement`)
    REFERENCES `SAE`.`Abonnement` (`idAbonnement`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Abonnement_has_Facture_Facture1`
    FOREIGN KEY (`Facture_idFacture`)
    REFERENCES `SAE`.`Facture` (`idFacture`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
