version: '1.0'
services:
  db:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build: ./backoffice
    environment:
      DATABASE_PASSWORD: password
    depends_on:
      - db

volumes:
    mysql-data:
      external: true
