version: '1.0'

services:
  express-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql-db
    restart: on-failure
  vue-frontend:
    build:
      context: ./frontend-vue/sakai-vue-3.9.0
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-vue/sakai-vue-3.9.0:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

  mysql-db:
    build:
      context: ../database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: SAE
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    external: true
